[project]
name = "tdf-monte-carlo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0",
    "click>=8.1.0",
    "pandas>=2.0.0"
]
